<table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#f2f2f2" style="direction:ltr;min-width:320px;text-align:center;color:#292c2e;font-family:-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif">
        <tbody><tr>
            <td bgcolor="#7000e3" style="padding:0;height:0" height="0">
                <div style="background:#7000e3;height:0;max-height:0;overflow:visible">
                    <div style="background:#7000e3;height:140px;width:100%"></div>
                </div>
            </td>
        </tr>
        <tr>
            <td bgcolor="#7000e3" style="padding:20px 0;color:#fff">
<img src="$site_logo" width="170" style="vertical-align:top;font-size:28px;color:#fff">
            </td>
        </tr>
        <tr>
            <td style="padding:0 20px;text-align:center">
                <span style="display:inline-block;vertical-align:top;width:100%;max-width:640px;text-align:left">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:640px;min-width:320px;margin:0 auto">
                        <tbody><tr>
                            <td>
                                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tbody><tr>
                                        <td style="text-align:center;color:#333844;font-size:16px">
                                            <table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tbody><tr>
        <td style="padding:8% 5% 0;text-align:center">
            <span style="display:inline-block;vertical-align:top">
    <table cellpadding="0" cellspacing="0" border="0">
        <tbody><tr>
            <td>
<table cellpadding="0" cellspacing="0" style="border-collapse:separate;margin:0 5px">
                    <tbody><tr>
                        <td width="80" bgcolor="#efefef" style="border-radius:50%;font-size:0" align="left">
                            <a href="$site_open" style="width:0;display:inline-block;vertical-align:top"><img width="80" src="$randomPhoto1" style="min-height:80px;vertical-align:top;border-radius:50%" border="0">
                            </a>                        
                            </td>
                    </tr>
                </tbody></table>
            </td>
            <td>
<table cellpadding="0" cellspacing="0" style="border-collapse:separate;margin:0 5px">
                    <tbody><tr>
                        <td width="80" bgcolor="#efefef" style="border-radius:50%;font-size:0" align="left">
                            <a href="$site_open" style="width:0;display:inline-block;vertical-align:top"><img width="80" src="$randomPhoto2" style="min-height:80px;vertical-align:top;border-radius:50%" border="0">
                            </a>                        
                            </td>
                    </tr>
                </tbody></table>
            </td>
            <td>
                <table cellpadding="0" cellspacing="0" style="border-collapse:separate;margin:0 5px">
                    <tbody><tr>
                        <td width="80" bgcolor="#efefef" style="border-radius:50%;font-size:0" align="left">
                            <a href="$site_open" style="width:0;display:inline-block;vertical-align:top"><img width="80" src="$randomPhoto3" style="min-height:80px;vertical-align:top;border-radius:50%" border="0">
                            </a>                        
                            </td>
                    </tr>
                </tbody></table>
            </td>
        </tr>
    </tbody></table>
</span>
        </td>
    </tr>
    <tr>
        <td style="padding:4% 5% 0;text-align:center">
            <span style="display:inline-block;vertical-align:top">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:480px;margin:0 auto">
                    <tbody><tr>
                        <td align="center">
                            <span style="font-size:22px;line-height:26px;color:#000">{lang}1{/lang}
                            </span>
                        </td>
                    </tr>
                </tbody></table>
            </span>
        </td>
    </tr>
    <tr>
        <td style="padding:2% 5% 3%;text-align:center">
            <span style="display:inline-block;vertical-align:top">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:420px;margin:0 auto">
                    <tbody><tr>
                        <td align="center">
                            <span style="font-size:16px;line-height:22px;color:#7f7f7f;display:inline-block;vertical-align:top;max-width:470px">{lang}2{/lang}
                            </span>
                        </td>
                    </tr>
                </tbody></table>
            </span>
        </td>
    </tr>
    <tr>
        <td style="padding:0 0 8%;text-align:center">
            <a href="$site_open" style="display:inline-block;padding:13px 30px;background:#17d417;text-decoration:none;border-radius:8px;color:#fff;font-weight:600;font-size:16px;text-align:center" target="_blank">{lang}3{/lang}
            </a>
        </td>
    </tr>
</tbody></table>
                                            <table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="100%">
                                                <tbody><tr>
                                                    <td style="text-align:center;padding:25px 0;border-top:1px solid #e5e5e5">
                                                        <table cellpadding="0" cellspacing="0" border="0" width="100%">
                                                            <tbody><tr>
                                                                <td style="padding:0 10px;width:33.33%;vertical-align:top;text-align:center">
                                                                    <a href="$site_ios" style="display:inline-block;text-decoration:none;color:#000;text-align:center;vertical-align:middle;margin:0 auto">
                                                                        <img src="app_store.png" height="32" alt="" border="0">
                                                                        <span style="font-size:14px;display:block;border-top:8px solid transparent;color:#6a6a6a">{lang}4{/lang}</span>
                                                                    </a>
                                                                </td>
                                                                <td style="padding:0 10px;width:33.33%;vertical-align:top;text-align:center">
                                                                    <a href="$site_gplay" style="display:inline-block;text-decoration:none;color:#000;text-align:center;vertical-align:middle;margin:0 auto">
                                                                        <img src="google_play.png" height="32" alt="" border="0">
                                                                        <span style="font-size:14px;display:block;border-top:8px solid transparent;color:#6a6a6a">{lang}5{/lang}</span>
                                                                    </a>
                                                                </td>
                                                                                                                          </tr>
                                                        </tbody></table>
                                                    </td>
                                                </tr>
                                            </tbody></table>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                                <tbody><tr>
                                                    <td style="padding:0 0 4%">
                                                        <span>
                                                            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                                                <tbody><tr>
                                                                    <td style="text-align:center;padding:25px 0 0">
                                                                        <div style="color:#000;display:block;font-size:14px;border-bottom:10px solid transparent">{lang}6{/lang}:</div>
                                                                        <a href="$site_facebook"> <img src="facebook.png" width="42" height="42" alt="Facebook" style="vertical-align:middle" border="0" class="CToWUd"></a>
                                                                        <a href="$site_twitter"><img src="twitter.png" width="42" height="42" alt="Twitter" style="vertical-align:middle" border="0" class="CToWUd"></a>
                                                                        <a href="$site_instagram"><img src="instagram.png" width="42" height="42" alt="Instagram" style="vertical-align:middle" border="0" class="CToWUd"></a>
                                                                    </td>
                                                                </tr>
                                                            </tbody></table>
                                                        </span>
                                                    </td>
                                                </tr>
                                            </tbody></table>
                                        </td>
                                    </tr>
                                </tbody></table>
                            </td>
                        </tr>
                    </tbody></table>
                </span>
            </td>
        </tr>
    </tbody></table>