<!DOCTYPE html>
<html>
<title><?php echo $sm['config']['title']; ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<link rel="icon" type="image/png" href="<?= $sm['theme']['favicon']['val']; ?>" sizes="32x32">
<link rel="stylesheet" href="<?php echo $sm['config']['site_url']; ?>themes/default/css/profileLanding.css"/>
<link rel="stylesheet" href="<?php echo $sm['config']['site_url']; ?>themes/default/css/crossplatform.css"/>
<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
<?php
$site_config = json_encode($sm['config']);
$site_plugins = json_encode($sm['plugins']);
$site_theme = json_encode($sm['theme']);
$site_lang = json_encode($sm['lang']);
$profile_info = json_encode($sm['profile']);
$seo_lang = json_encode($sm['seoLang']);

echo 
'<script>
var url;
var totalDiscoverStories = 0;
var nextStory = 0;
var storyPage = "";
var mobileSite = false;
var siteUrl = "'.$sm['config']['site_url'].'";
var site_config = '. $site_config  . ';
var plugins = '. $site_plugins  . ';
var site_theme = '. $site_theme  . ';
var site_lang = '. $site_lang  . ';
var profile_info = '.$profile_info.';
var seo_lang = '. $seo_lang  . ';
function request_source(){
    return \'' . $sm['config']['ajax_path'] . '\';
}
function site_title(){
    return \'' . $sm['config']['title'] . '\';
}   
function theme_source(){
    return \'' . $sm['config']['theme_url'] . '\';
}
function site_url(){
    return \'' . $sm['config']['site_url'] . '\';
}   
</script>';
?>
<style>
body{
  height: 500px;
}
.bg-image{
  background-image:url("");
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  background: #fafafa;
}
.landing__profilePhoto{
  background-image:url("<?= profilePhoto($sm['profile']['id'],1); ?>");
  background-repeat: no-repeat;
  background-size: cover;
}
.landing__footer{
  position: absolute;
  bottom: 0;
  width: 100%;
  left: 0;
  height: 120px;
  text-align: center;
}
.footerLanding{
position:fixed;bottom:-20px;left:0;width:100%;max-width:600px;left: 50%;
transform: translateX(-50%);z-index: 99;
}
.storyOn{
  stroke: <?= $sm['theme']['story_on_landing']['val'];?> !important;
}
@keyframes color {
  100%,
  0% {
    stroke: <?= $sm['theme']['story_on_landing']['val'];?>;
  }
  90% {
    stroke: <?= $sm['theme']['story_on_landing']['val'];?>
  }
}

.storyOff{
  stroke: <?= $sm['theme']['story_off_landing']['val'];?> !important;
  stroke-width:1px !important;
}
.profileBio{
    color: <?=$sm['theme']['profileOff_bio_font_color']['val']; ?> !important;    
    font-family: '<?= $sm['theme']['profileOff_bio_font']['val']; ?>' !important;
    font-size: <?= $sm['theme']['profileOff_bio_fontSize']['val']; ?>px !important; 
}
.profileName{    
    font-family: '<?= $sm['theme']['profileOff_bio_font']['val']; ?>' !important;
    font-size: <?= $sm['theme']['profileOff_bio_fontSize']['val']*1.45; ?>px !important; 
}
.profileRegister{
    color: <?=$sm['theme']['profileOff_register_font_color']['val']; ?> !important;    
    font-family: '<?= $sm['theme']['profileOff_register_font']['val']; ?>' !important;
    font-size: <?= $sm['theme']['profileOff_register_fontSize']['val']; ?>px !important; 
}
</style>
<?php $fonts = getArrayDSelected('font','theme_preset_fonts','where preset = "'.$_SESSION['preset'].'"');
foreach ($fonts as $font) { 
    $f = $font['font'];
    $f = str_replace(' ','+', $f);
    echo '<link href="https://fonts.googleapis.com/css?family='.$f.'" rel="stylesheet" type="text/css"/>';
} ?>
</head>
<body class="<?=$sm['theme']['profileOff_bg']['val']; ?>" style="background: <?=$sm['theme']['profileOff_bg']['val']; ?>">
<div class="landing">
  <div class="landingLogo">
    <a href="<?= $sm['config']['site_url']; ?>"><img class="responsive-img" src="<?= $sm['theme']['profileOff_logo']['val']; ?>" style="max-width: 180px" /></a>
  </div>

  <div class="landing__content">
    <div class="landing__profilePhoto hasStory box-shadow-left-profile" onclick="openStory(<?= $sm['profile']['story']; ?>,<?= $sm['profile']['id']; ?>)">
      <div class="roller" data-storyRoller data-loading-story style="display: none"></div>
      <div class="over-roller" data-storyPath data-loading-story style="display: none"></div>          
    </div>
    <h2 class="profileName" style="margin-top: 35px;color: <?= $sm['theme']['profileOff_color']['val']; ?>">
      <?= $sm['profile']['first_name']; ?>,<?= $sm['profile']['age']; ?>   
    </h2>    
    <h3 class="landing__text profileBio <?=$sm['theme']['profileOff_bio_bg']['val']; ?>" style="margin-top: 10px;background: <?=$sm['theme']['profileOff_bio_bg']['val']; ?>">
      <?php if(empty($sm['profile']['bio'])){ ?>
        <?= $sm['lang'][814]['text']; ?>
      <?php } else { ?>
        <?= $sm['profile']['bio']; ?>        
      <?php } ?>
    </h3>
  </div>

</div>

<div class="footerLanding <?=$sm['theme']['profileOff_bg']['val']; ?>" style="background: <?=$sm['theme']['profileOff_bg']['val']; ?>;color: <?=$sm['theme']['profileOff_color']['val']; ?>"> 
  <h3>
    <?= $sm['lang'][815]['text']; ?> <?= $sm['config']['name']; ?>.
  </h3>
  <a class="btn profileRegister <?=$sm['theme']['profileOff_register_bg']['val']; ?>" style="background: <?=$sm['theme']['profileOff_register_bg']['val']; ?>;max-width: 100%;border-radius: 3px;text-align: center;" href="<?= $sm['config']['site_url']; ?>"><strong><?= $sm['lang'][816]['text']; ?></strong></a>  
</div>

<?php if($sm['theme']['preload_enable']['val'] == 'Yes'){ ?> 
    <div id="preloader-container" style="background: <?= $sm['theme']['preload_bg']['val']; ?>;"><div id="preloader"><img class="icon" src="<?= $sm['theme']['preload_image']['val']; ?>">
    </div></div>    
<?php } ?>

<!-- cookies -->
<?php if($sm['plugins']['terms']['showCookies'] == 'Yes'){ ?>
    <?= getAbsolutePage('terms/cookiesLaw'); ?>
<?php } ?>

<div id="storytime" data-story="0"></div>
<div id="loadingImages" style="position: absolute;width: 1px;height: 1px;overflow: hidden">
</div>
<script src="<?php echo $sm['config']['theme_url']; ?>/js/vendor/jquery-2.1.1.js"></script>
<script src="<?php echo $sm['config']['theme_url']; ?>/js/vendor/jquery.dm-uploader.min.js"></script>
<?php foreach($sm['plugin'] as $plugin){ ?>
    <?php if(!empty($plugin['js_file'])){
echo '<script src="'.$sm['config']['site_url'].'themes/plugins/'.$plugin['js_file'].'.js"></script>';
            } 
    } ?>

<script type="text/javascript">  
var currentStory;
var socialStory = new Story({
    playlist: currentStory
}); 

storyLoader(<?= $sm['profile']['story']; ?>,'<?= $sm['profile']['stories']; ?>',<?= $sm['profile']['status_info']; ?>);    

$(window).on('load', function() {
    var h = $('html').height();
    h = h +200;
    $('.bg-image').css('height',h+'px');
    $('#preloader-container').delay(275).fadeOut('slow');

    document.title = profile_info.name + ", " + profile_info.age + ", " + profile_info.city + " | " + seo_lang['profile'][1]['text'];
    $("meta[property='og\\:title']").attr('content',  profile_info.name + ", " + profile_info.age + ", " + profile_info.city + " | " + seo_lang['profile'][1]['text']);
    if(profile_info.username == ''){
      profile_info.username = profile_info.id;
    }
    $("meta[property='og\\:url']").attr('content',  site_config.site_url+'@'+profile_info.username);
    $("meta[property='og\\:image']").attr('content',  profile_info.profile_photo);
    $("meta[property='og\\:description']").attr('content',  seo_lang['profile'][2]['text']);

    <?php if(isset($_GET['s'])){
      $storiesFilter = 'WHERE id = '.$_GET['s'];
      $data = getUserStories( $sm['profile']['first_name'], $sm['profile']['profile_photo'],$storiesFilter,'storyTime ASC');
      echo 'openStoryLanding('.json_encode($data).'); storyLoaderLanding();
      ';
    } else { ?>

    <?php }?>    
});

</script>
</body>
</html>