#loading{
     background: rgba(255,255,255,1);
}

.load-circle span:after {
  border: 5px solid #ffffff;
  border-color: #000 transparent #000 transparent;
}

.omga-02__hero-area {
  background: url('<?= $sm['landing']['background_image2']['val']; ?>') no-repeat;
  background-size: cover;
}

.border-radius-50{
    border-radius:50% !important;
}

.border-radius-15{
    border-radius: 15px !important;
}

.maxH-650 {
    max-height: 650px;
    min-height: 650px;
}

.m-t-48{
    margin-top: -48px;
}

.header1_h2{
    color: #fff !important;
}

.header1_p{
    color: #fff !important;
}

.nav-btn-bg{

}

.nav-btn-bg span{

}


.header-text-bg{
    padding:15px;
    background:rgba(0,0,0,.3);
    border-radius:5px;
    margin-top:25px;
    color:#fff !important;
}

.color-dark{
    color: #333 !important;
}

.terms-note{
    padding-top:15px;
    padding-bottom:25px;
}

.big-form{
    font-size:1.5rem;
}

.float-right{
    float:right;
}

.modal-form-btn{
    background: #f04037;border: none;font-size: 16px;
}

.display-none{
    display:none;
}

.modal-height{
    height: 600px !important;
}