<html>
	<head>
		<title><?= $sm['lang'][624]['text']; ?> | <?php echo $sm['config']['name']; ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
	</head>
	<body class="landing">
		<section id="cta">
			<center>
				<h2><?= $sm['config']['name'];?></h2>
				<h3><?= $sm['lang'][624]['text']; ?></h3>
				<?= $sm['plugins']['terms']['cookies']; ?>
			</center>
		</section>						
	</body>
</html>