<script>
    aurl = 'main_dashboard';
    currentMenu = 'main';
    currentMenuCollapse = 'dashboard';
</script>
<?php 
global $mysqli;
$time_now = time()-300;
$today = date('w'); 
$filterWithFakeUsers = 'where last_access >= '.$time_now.' || fake = 1 and online_day = '.$today;
$filterWithFakeUsers = 'where last_access >= '.$time_now;
$onlineUsersTotal = selectC('users',$filterWithFakeUsers);
$onlineUsersReal = selectC('users',$filterWithFakeUsers);

$allDay = time()-86400;

$todayRevenueFilter = 'where time > '.$allDay;
$todayRevenue = selectSum('sales','amount',$todayRevenueFilter);

$todayDate = date('m/d/Y', time());
$newAccountsFilter = 'where join_date = "'.$todayDate.'"';
$newAccounts = selectC('users',$newAccountsFilter);

$seven = 86400*7;
$sevenDays = time()-$seven;
$lastSevenDaysFilter = 'where join_date_time >= "'.$sevenDays.'"';
$lastSevenDays = selectC('users',$lastSevenDaysFilter );

$lastSevenDaysFilterSales = 'where time >= "'.$sevenDays.'"';
$lastSevenDaysSales = selectC('sales',$lastSevenDaysFilterSales );

$lastSevenDaysChartUsers = '';
$lastSevenDaysChartSales = '';

$m= date("m");
$de= date("d");
$y= date("Y");

$arrLastSevenDaysUsers = array();
for($i = 7; $i > 0; $i--){
    $date = date('m/d/Y',mktime(0,0,0,$m,($de-$i),$y)); 
    $filterUser = 'where join_date = "'.$date.'"';
    $queryUser = selectC('users',$filterUser);
    $lastSevenDaysChartUsers.= $queryUser.',';
    array_push($arrLastSevenDaysUsers, $queryUser);


    $filterSale = 'where saledate = "'.$date.'"';
    $querySales = selectC('sales',$filterSale);
    $lastSevenDaysChartSales.= $querySales.',';    
}   

$lastSevenDaysChartUsers = substr_replace($lastSevenDaysChartUsers ,"", -1);
$lastSevenDaysChartSales = substr_replace($lastSevenDaysChartSales ,"", -1);
echo '<script>lastSevenDaysChartUsers = '.json_encode($arrLastSevenDaysUsers).';</script>';
?>

<!-- SECTION CONTENT -->
<div class="container-fluid page__container" data-main-dashboard style="padding-top:25px ">

<?php if(isset($_GET['updated'])){

$client = [];
$url='https://www.premiumdatingscript.com/clients/client.php?'.
    'url=' . urlencode($_SERVER["HTTP_HOST"]) .
    '&license=' . urlencode($sm['settings']['license']) .
    '&type=' . urlencode('envato');

if (function_exists('curl_get_contents') && function_exists('curl_init')) {
    $callApi = curl_get_contents($url);
    if(!empty($callApi)){
        $client = json_decode($callApi);

        if(isset($client->active)){
            
            if($client->active == 0){
                updateData('settings','setting_val',$client->reason,'WHERE setting = "licenseError"');
                $licenseErrorHtml = str_replace('[INVALID-MESSAGE]', $client->reason, $licenseErrorHtml);
                $licenseErrorHtml = str_replace('[INVALID-TITLE]', 'INVALID DOMAIN', $licenseErrorHtml);
                echo $licenseErrorHtml;                         
                exit;               
            }

            updateData('client','client',json_encode($callApi,JSON_UNESCAPED_UNICODE));

            updateData('settings','setting_val',$client->fakeUsers,'WHERE setting = "fakeUserLimit"');
            updateData('settings','setting_val',$client->fakeUsersUsage,'WHERE setting = "fakeUserUsage"');
            updateData('settings','setting_val',$client->premium,'WHERE setting = "premium"');
            updateData('settings','setting_val',$client->domainsLimit,'WHERE setting = "domainsLimit"');
            updateData('settings','setting_val',$client->domainsUsage,'WHERE setting = "domainsUsage"');

        }

    }
}
$languages = getArray('languages','where id <> 1','id desc');
if(!empty($languages)){
    foreach ($languages as $lang) {
        $langTables = ['site_lang','app_lang','email_lang','landing_lang','seo_lang'];
            foreach ($langTables as $table) {        
                $english = getArray($table,'where lang_id = 1','id desc');
                $current = getArray($table,'where lang_id = "'.$lang['id'].'"','id desc');


                $englishIds = array();
                foreach ($english as $eng) {
                    array_push($englishIds, $eng['id']);
                }
                $currentIds = array();
                foreach ($current as $curr) {
                    array_push($currentIds, $curr['id']);
                }        
                $diff=array_diff($englishIds,$currentIds);

                if($table == 'landing_lang'){
                    $landing = getArray($table,'where lang_id = 1','id desc');
                    foreach ($landing as $l) {

                        $theme = getData($table,'theme','WHERE lang_id = 1 AND theme = "'.$l['theme'].'" AND id = '.$l['id']);
                        $preset = getData($table,'preset','WHERE lang_id = 1 AND theme = "'.$l['theme'].'" AND id = '.$l['id']);
                        $text = getData($table,'text','WHERE lang_id = 1 AND id = '.$l['id']);
                        $mysqli->query('INSERT INTO '.$table.' (id,lang_id,text,theme,preset)  VALUES ('.$l['id'].','.$lang['id'].',"'.$text.'","'.$theme.'","'.$preset.'")');
                    }
                }

                if(!empty($diff)){
                foreach ($diff as $val) {
                    $text = getData($table,'text','WHERE lang_id = 1 AND id = '.$val);
                    $mysqli->query('INSERT INTO '.$table.' (id,lang_id,text) VALUES ('.$val.','.$lang['id'].',"'.$text.'")');                        
                }
            }
        }
    } 
}
?>

<div class="alert alert-soft-primary alert-dismissible d-flex align-items-center card-margin"  style="cursor: pointer;" onclick="goTo('update')" data-update-software-main-dashboard>
    <i class="material-icons mr-3">update</i>
    <div class="text-body">Software updated<br>Updated to version <?= $_GET['updated']; ?></div>
</div>

<?php } ?>

<?php 
    
    //$mysqli->query('UPDATE activity SET time = "'.time().'" WHERE id = "'.$value['id'].'"');

    $checkUpdateFilter = time()-3600;
    if($sm['settings']['checkUpdate'] < $checkUpdateFilter && $sm['settings']['updateAvailable'] != 'Yes'){ 
    $url='https://premiumdatingscript.com/clients/updates.php?'.
        'd=' . urlencode($_SERVER['HTTP_HOST']) .
        '&l=' . urlencode($sm['settings']['license']) .
        '&v=' . urlencode($sm['settings']['currentVersion']);
        $callApi = curl_get_contents($url);
        $api = json_decode($callApi);
        if($api->version > $sm['settings']['currentVersion']){ 
            $mysqli->query('UPDATE settings SET setting_val = "Yes" WHERE setting = "updateAvailable"');
            $mysqli->query('UPDATE settings SET setting_val = "'.time().'" WHERE setting = "checkUpdate"');
        ?>
            <div class="alert alert-soft-success alert-dismissible d-flex align-items-center card-margin"  style="cursor: pointer;" onclick="goTo('update')" data-update-software-main-dashboard>
                <i class="material-icons mr-3">update</i>
                <div class="text-body">Software update available<br>
                    New version <span id="newVersionUpdate"><?= $api->version; ?></span><br>
                    <strong>Click here for <a href="#">go to the update page</a></strong></div>
            </div>
        <?php } else {
            $mysqli->query('UPDATE settings SET setting_val = "No" WHERE setting = "updateAvailable"');
            $mysqli->query('UPDATE settings SET setting_val = "'.time().'" WHERE setting = "checkUpdate"');
        }
 } ?>

 <?php if($sm['settings']['updateAvailable'] == 'Yes' && $sm['user']['admin'] == 1 ){ ?>
    <div class="alert alert-soft-success alert-dismissible d-flex align-items-center card-margin"  style="cursor: pointer;" onclick="goTo('update')" data-update-software-main-dashboard>
        <i class="material-icons mr-3">update</i>
        <div class="text-body">Software update available<br>
            <strong>Click here for <a href="#">go to the update page</a></strong></div>
    </div>
 <?php } ?>



    <div class="row card-group-row">
        <div class="col-lg-4 col-md-6 card-group-row__col">
            <div class="card card-group-row__card card-body card-body-x-lg flex-row align-items-center">
                <div class="flex">
                    <div class="card-header__title text-muted mb-2">Online Users</div>
                    <div class="text-amount"><?= number_format($onlineUsersTotal); ?></div>
                </div>
                <div><i class="material-icons icon-muted icon-40pt ml-3">gps_fixed</i></div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 card-group-row__col">
            <div class="card card-group-row__card card-body card-body-x-lg flex-row align-items-center">
                <div class="flex">
                    <div class="card-header__title text-muted mb-2">Today Revenue</div>
                    <div class="text-amount"><?= $sm['plugins']['settings']['currencySymbol']; ?><?= $todayRevenue; ?></div>
                    <!--<div class="text-stats text-success">51.5% <i class="material-icons">arrow_upward</i></div>-->
                </div>
                <div><i class="material-icons icon-muted icon-40pt ml-3">monetization_on</i></div>
            </div>
        </div>
        <div class="col-lg-4 col-md-12 card-group-row__col">
            <div class="card card-group-row__card card-body card-body-x-lg flex-row align-items-center">
                <div class="flex">
                    <div class="card-header__title text-muted mb-2">Today New Accounts</div>
                    <div class="text-amount"><?= $newAccounts; ?></div>

                </div>
                <div><i class="material-icons icon-muted icon-40pt ml-3">perm_identity</i></div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-5">
              <div class="card-header card-header-large bg-white">
                    <h4 class="card-header__title">Latest 7 days statics</h4>
                </div>                                
            <div class="card dashboard-area-tabs" id="dashboard-area-tabs">
                <div class="card-header p-0 bg-white nav">
                    <div class="row no-gutters flex" role="tablist">
                        <div class="col" data-toggle="chart" id="usersChart" data-target="#mainDashChart" data-update='{"data":{"datasets":[{"label": "Traffic", "data":[<?= $lastSevenDaysChartUsers; ?>]}]}}' data-prefix="" data-suffix="">
                            <a href="#" data-toggle="tab" role="tab" aria-selected="true" class="dashboard-area-tabs__tab card-body text-center active">
                                <span class="card-header__title m-0">New users</span>
                                <span class="text-amount"><?= number_format($lastSevenDays); ?></span>
                            </a>
                        </div>
                        <div class="col border-left" data-toggle="chart" data-target="#mainDashChart" data-update='{"data":{"datasets":[{"label": "Earnings", "data":[<?= $lastSevenDaysChartSales; ?>]}]}}' data-prefix="$" data-suffix="">
                            <a href="#" data-toggle="tab" role="tab" aria-selected="false" class="dashboard-area-tabs__tab card-body text-center">
                                <span class="card-header__title m-0">Sales</span>
                                <span class="text-amount"><?= $sm['plugins']['settings']['currencySymbol']; ?><?= number_format($lastSevenDaysSales); ?></span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body text-muted" style="height: 280px;">
                    <div class="chart" style="height: calc(280px - 1.25rem * 2);">
                        <canvas id="mainDashChart">
                            <span style="font-size: 1rem;"><strong>Website Traffic / Earnings</strong> area chart goes here.</span>
                        </canvas>
                    </div>
                </div>
            </div>



            <div class="card-group">
                <div class="card card-body text-center">
                    <div class="mb-1"><i class="material-icons icon-muted icon-40pt">people</i></div>
                    <div class="text-amount"><?php echo number_format(selectC('users')); ?></div>
                    <div class="card-header__title mb-2">Accounts</div>
                </div>
                <div class="card card-body text-center">
                    <div class="mb-1"><i class="material-icons icon-muted icon-40pt">monetization_on</i></div>
                    <div class="text-amount"><?= $sm['plugins']['settings']['currencySymbol']; ?><?php echo number_format(selectSum('sales','amount')); ?></div>
                    <div class="card-header__title  mb-2">Lifetime Revenue in <?= $sm['settings']['currency'];?></div>
                </div>
            </div>
        </div>


        <?php if($sm['plugins']['logActivity']['enabled'] == 'Yes'){ ?>
        <div class="col-lg-7">
            <div class="card">
                <div class="card-header card-header-large bg-white d-flex align-items-center">
                    <h4 class="card-header__title flex m-0">Recent Activity</h4>
                </div>
                <div class="card-header card-header-tabs-basic nav" role="tablist">
                    <a href="#activity_all" class="active" data-toggle="tab" role="tab" aria-controls="activity_all" aria-selected="true">All</a>
                    <a href="#activity_system" data-toggle="tab" role="tab" aria-controls="activity_system" aria-selected="false">System</a>                    
                    <a href="#activity_purchases" data-toggle="tab" role="tab" aria-controls="activity_purchases" aria-selected="false">Purchases</a>
                    <a href="#activity_messages" data-toggle="tab" role="tab" aria-controls="activity_messages" aria-selected="false">Chat</a>
                    <a href="#activity_likes" data-toggle="tab" role="tab" aria-controls="activity_likes" aria-selected="false">Likes</a>
                    <a href="#activity_visits" data-toggle="tab" role="tab" aria-controls="activity_visits" aria-selected="false">Visits</a>                                        
                </div>
                <div class="list-group tab-content list-group-flush" style="overflow-y: scroll;height: 515px">
                    <div class="tab-pane active show fade" id="activity_all">

                    <?php 
                    //latest activity all

                    $latestActivityAll = getArray('activity','','id desc','limit 0,50'); 

                    foreach ($latestActivityAll as $value) { 

                        if($value['time'] == null || $value['time'] == ''){
                            $value['time'] = time();
                            $mysqli->query('UPDATE activity SET time = "'.time().'" WHERE id = "'.$value['id'].'"');
                        } ?>

                        <?php if($value['a_type'] == 'system'){ ?>
                        <div class="list-group-item list-group-item-action d-flex align-items-center" data-latest-activity="system">
                            <div class="avatar avatar-xs mr-3">
                                <span class="avatar-title rounded-circle  bg-dark">
                                    <i class="material-icons">settings</i>
                                </span>
                            </div>

                            <div class="flex">
                                <div class="d-flex align-items-middle">                                    
                                    <strong class="text-15pt mr-1"><?= $value['title']; ?></strong>
                                </div>
                                <small><?= $value['message']; ?></small>
                            </div>
                            <small class="text-muted"><?= time_elapsed_string($value['time']); ?></small>
                            <i class="material-icons icon-muted ml-3">arrow_forward</i>
                        </div>                            
                        <?php } ?>

                        <?php if($value['a_type'] == 'visit'){ ?>
                        <?php $info = json_decode($value['message'], true); ?>
                        <div class="list-group-item list-group-item-action d-flex align-items-center" data-latest-activity="visit">
                            <div class="avatar avatar-xs mr-3">
                                <span class="avatar-title rounded-circle  bg-purple">
                                    <i class="material-icons">visibility</i>
                                </span>
                            </div>

                            <div class="flex">
                                <div class="d-flex align-items-middle">
                                    <div class="avatar avatar-xxs mr-1">
                                        <img src="<?= $info['u1']['photo']; ?>" class="avatar-img rounded-circle">
                                    </div>
                                    <div class="avatar avatar-xxs mr-1">
                                        <img src="<?= $info['u2']['photo']; ?>" class="avatar-img rounded-circle">
                                    </div>                                    
                                    <strong class="text-15pt mr-1"><?= $value['title']; ?></strong>

                                </div>
                                <small><a href="#"><?= unicode2html($info['u1']['name']); ?></a> visited <a href="#"><?= unicode2html($info['u2']['name']); ?></a></small>
                            </div>
                            <small class="text-muted"><?= time_elapsed_string($value['time']); ?></small>
                            <i class="material-icons icon-muted ml-3">arrow_forward</i>
                        </div>                            
                        <?php } ?>

                        <?php if($value['a_type'] == 'message'){ ?>

                            <?php $info = json_decode($value['message'], true); ?>
                            <div class="list-group-item list-group-item-action d-flex align-items-center" data-latest-activity="message">
                                <div class="avatar avatar-xs mr-3">
                                    <span class="avatar-title rounded-circle  bg-info">
                                        <i class="material-icons">message</i>
                                    </span>
                                </div>

                                <div class="flex">
                                    <div class="d-flex align-items-middle">
                                        <div class="avatar avatar-xxs mr-1">
                                            <img src="<?= $info['u1']['photo']; ?>" class="avatar-img rounded-circle">
                                        </div>
                                        <div class="avatar avatar-xxs mr-1">
                                            <img src="<?= $info['u2']['photo']; ?>" class="avatar-img rounded-circle">
                                        </div>                                    
                                        <strong class="text-15pt mr-1"><?= $value['title']; ?></strong>

                                    </div>
                                    <small><?= unicode2html($info['message']); ?></small>
                                </div>
                                <small class="text-muted"><?= time_elapsed_string($value['time']); ?></small>
                                <i class="material-icons icon-muted ml-3">arrow_forward</i>
                            </div>                           

                        <?php } ?> 

                        <?php if($value['a_type'] == 'sale'){ ?>
                            <?php $info = json_decode($value['message'], true); ?>
                            <div class="list-group-item list-group-item-action d-flex align-items-center">
                                <div class="avatar avatar-xs mr-3">
                                    <span class="avatar-title rounded-circle  bg-warning">
                                        <i class="material-icons">attach_money</i>
                                    </span>
                                </div>

                                <div class="flex">
                                    <div class="d-flex align-items-middle">
                                        <div class="avatar avatar-xxs mr-1">
                                            <img src="<?= $info['sale']['photo']; ?>" class="avatar-img rounded-circle">
                                        </div>                                  
                                        <strong class="text-15pt mr-1"><?= $value['title']; ?></strong>

                                    </div>
                                    <small><a href="#"><?= unicode2html($info['sale']['name']); ?></a> purchased <?= $info['sale']['amount']; ?> credits with <?= $info['sale']['method']; ?></small>
                                </div>
                                <small class="text-muted"><?= time_elapsed_string($value['time']); ?></small>
                                <i class="material-icons icon-muted ml-3">arrow_forward</i>
                            </div> 
                        <?php } ?> 

                        <?php if($value['a_type'] == 'like'){ ?>                                       
                            <?php $info = json_decode($value['message'], true); ?>
                            <div class="list-group-item list-group-item-action d-flex align-items-center">
                                <div class="avatar avatar-xs mr-3">
                                    <span class="avatar-title rounded-circle  bg-danger">
                                        <i class="material-icons">favorite</i>
                                    </span>
                                </div>

                                <div class="flex">
                                    <div class="d-flex align-items-middle">
                                        <div class="avatar avatar-xxs mr-1">
                                            <img src="<?= $info['u1']['photo']; ?>" class="avatar-img rounded-circle">
                                        </div>
                                        <div class="avatar avatar-xxs mr-1">
                                            <img src="<?= $info['u2']['photo']; ?>" class="avatar-img rounded-circle">
                                        </div>                                    
                                        <strong class="text-15pt mr-1"><?= $value['title']; ?></strong>

                                    </div>
                                    <small><a href="#"><?= unicode2html($info['u1']['name']); ?></a> liked <a href="#"><?= unicode2html($info['u2']['name']); ?></a></small>
                                </div>
                                <small class="text-muted"><?= time_elapsed_string($value['time']); ?></small>
                                <i class="material-icons icon-muted ml-3">arrow_forward</i>
                            </div>                                                    
                        <?php } ?>                                                     

                   <?php } ?>

                    </div>

                    <div class="tab-pane" id="activity_system">
                    <?php 

                    //latest activity system

                    $latestActivitySystem = getArray('activity','where a_type = "system"','time desc','limit 0,50'); 

                    foreach ($latestActivitySystem as $value) { ?>

                        <div class="list-group-item list-group-item-action d-flex align-items-center" data-adminurl="activity">
                            <div class="avatar avatar-xs mr-3">
                                <span class="avatar-title rounded-circle  bg-dark">
                                    <i class="material-icons">settings</i>
                                </span>
                            </div>

                            <div class="flex">
                                <div class="d-flex align-items-middle">                                    
                                    <strong class="text-15pt mr-1"><?= $value['title']; ?></strong>
                                </div>
                                <small><?= unicode2html($value['message']); ?></small>
                            </div>
                            <small class="text-muted"><?= time_elapsed_string($value['time']); ?></small>
                            <i class="material-icons icon-muted ml-3">arrow_forward</i>
                        </div>                            

                    <?php } ?>

                    </div>

                    <div class="tab-pane" id="activity_purchases">
                    <?php 

                    //latest activity purchases

                    $latestActivitySale = getArray('activity','where a_type = "sale"','time desc','limit 0,50'); 

                    foreach ($latestActivitySale as $value) { ?>
                        <?php $info = json_decode($value['message'], true); ?>
                        <div class="list-group-item list-group-item-action d-flex align-items-center ">
                            <div class="avatar avatar-xs mr-3">
                                <span class="avatar-title rounded-circle  bg-warning">
                                    <i class="material-icons">attach_money</i>
                                </span>
                            </div>

                            <div class="flex">
                                <div class="d-flex align-items-middle">
                                    <div class="avatar avatar-xxs mr-1">
                                        <img src="<?= $info['sale']['photo']; ?>" class="avatar-img rounded-circle">
                                    </div>                                  
                                    <strong class="text-15pt mr-1"><?= $value['title']; ?></strong>

                                </div>
                                <small><a href="#"><?= unicode2html($info['sale']['name']); ?></a> purchased <?= $info['sale']['amount']; ?> credits with <?= $info['sale']['method']; ?></small>
                            </div>
                            <small class="text-muted"><?= time_elapsed_string($value['time']); ?></small>
                            <i class="material-icons icon-muted ml-3">arrow_forward</i>
                        </div>                            

                   <?php } ?>

                    </div>
                    <div class="tab-pane" id="activity_messages">

                    <?php
                    //latest activity purchases

                    $latestActivityMessages = getArray('activity','where a_type = "message"','time desc','limit 0,50'); 

                    foreach ($latestActivityMessages as $value) { ?>
                        <?php $info = json_decode($value['message'], true); ?>
                        <div class="list-group-item list-group-item-action d-flex align-items-center ">
                            <div class="avatar avatar-xs mr-3">
                                <span class="avatar-title rounded-circle  bg-info">
                                    <i class="material-icons">message</i>
                                </span>
                            </div>

                            <div class="flex">
                                <div class="d-flex align-items-middle">
                                    <div class="avatar avatar-xxs mr-1">
                                        <img src="<?= $info['u1']['photo']; ?>" class="avatar-img rounded-circle">
                                    </div>
                                    <div class="avatar avatar-xxs mr-1">
                                        <img src="<?= $info['u2']['photo']; ?>" class="avatar-img rounded-circle">
                                    </div>                                    
                                    <strong class="text-15pt mr-1"><?= $value['title']; ?></strong>

                                </div>
                                <small><?= unicode2html($info['message']); ?></small>
                            </div>
                            <small class="text-muted"><?= time_elapsed_string($value['time']); ?></small>
                            <i class="material-icons icon-muted ml-3">arrow_forward</i>
                        </div>                           

                   <?php } ?>   

                    </div>

                    <div class="tab-pane" id="activity_likes">

                        <?php 
                        $latestActivityVisits = getArray('activity','where a_type = "like"','time desc','limit 0,50'); 

                        foreach ($latestActivityVisits as $value) { ?>                                         
                            <?php $info = json_decode($value['message'], true); ?>
                            <div class="list-group-item list-group-item-action d-flex align-items-center">
                                <div class="avatar avatar-xs mr-3">
                                    <span class="avatar-title rounded-circle  bg-danger">
                                        <i class="material-icons">favorite</i>
                                    </span>
                                </div>

                                <div class="flex">
                                    <div class="d-flex align-items-middle">
                                        <div class="avatar avatar-xxs mr-1">
                                            <img src="<?= $info['u1']['photo']; ?>" class="avatar-img rounded-circle">
                                        </div>
                                        <div class="avatar avatar-xxs mr-1">
                                            <img src="<?= $info['u2']['photo']; ?>" class="avatar-img rounded-circle">
                                        </div>                                    
                                        <strong class="text-15pt mr-1"><?= $value['title']; ?></strong>

                                    </div>
                                    <small><a href="#"><?= unicode2html($info['u1']['name']); ?></a> liked <a href="#"><?= unicode2html($info['u2']['name']); ?></a></small>
                                </div>
                                <small class="text-muted"><?= time_elapsed_string($value['time']); ?></small>
                                <i class="material-icons icon-muted ml-3">arrow_forward</i>
                            </div>                                                    
                        <?php } ?>                        

                    </div>


                    <div class="tab-pane" id="activity_visits">
                    
                    <?php 
                    $latestActivityVisits = getArray('activity','where a_type = "visit"','time desc','limit 0,50'); 

                    foreach ($latestActivityVisits as $value) { ?>                                         
                        <?php $info = json_decode($value['message'], true); ?>
                        <div class="list-group-item list-group-item-action d-flex align-items-center" >
                            <div class="avatar avatar-xs mr-3">
                                <span class="avatar-title rounded-circle  bg-purple">
                                    <i class="material-icons">visibility</i>
                                </span>
                            </div>

                            <div class="flex">
                                <div class="d-flex align-items-middle">
                                    <div class="avatar avatar-xxs mr-1">
                                        <img src="<?= $info['u1']['photo']; ?>" class="avatar-img rounded-circle">
                                    </div>
                                    <div class="avatar avatar-xxs mr-1">
                                        <img src="<?= $info['u2']['photo']; ?>" class="avatar-img rounded-circle">
                                    </div>                                    
                                    <strong class="text-15pt mr-1"><?= $value['title']; ?></strong>

                                </div>
                                <small><a href="#"><?= unicode2html($info['u1']['name']); ?></a> visited <a href="#"><?= unicode2html($info['u2']['name']); ?></a></small>
                            </div>
                            <small class="text-muted"><?= time_elapsed_string($value['time']); ?></small>
                            <i class="material-icons icon-muted ml-3">arrow_forward</i>
                        </div>                                                    
                    <?php } ?>      
                    </div>
                </div>
            </div>


        </div>

        <?php } else { ?>
        <div class="col-lg-5">
            <div class="card">
                <div class="card-header card-header-large bg-white d-flex align-items-center">
                    <h4 class="card-header__title flex m-0">Recent Activity</h4>
                </div>
                <div class="card-header card-header-tabs-basic nav" role="tablist">
                    <a href="#activity_all" class="active" data-toggle="tab" role="tab" aria-controls="activity_all" aria-selected="true">All</a>
                    <a href="#activity_system" data-toggle="tab" role="tab" aria-controls="activity_system" aria-selected="false">System</a>                    
                    <a href="#activity_purchases" data-toggle="tab" role="tab" aria-controls="activity_purchases" aria-selected="false">Purchases</a>
                    <a href="#activity_messages" data-toggle="tab" role="tab" aria-controls="activity_messages" aria-selected="false">Messages</a>
                    <a href="#activity_likes" data-toggle="tab" role="tab" aria-controls="activity_likes" aria-selected="false">Likes</a>
                    <a href="#activity_visits" data-toggle="tab" role="tab" aria-controls="activity_visits" aria-selected="false">Visits</a>                                        
                </div>
                <div class="list-group tab-content list-group-flush" style="overflow-y: scroll;height: 515px">
                    <div class="tab-pane active show fade" id="activity_all">
                        <div class="list-group-item list-group-item-action d-flex align-items-center">
                            <div class="avatar avatar-xs mr-3">
                                <span class="avatar-title rounded-circle  bg-dark">
                                    <i class="material-icons">settings</i>
                                </span>
                            </div>

                            <div class="flex">
                                <div class="d-flex align-items-middle">                                    
                                    <strong class="text-15pt mr-1">Activity log disabled</strong>
                                </div>
                                <small>Enable the activity log from the plugin manager</small>
                            </div>
                            <i class="material-icons icon-muted ml-3">arrow_forward</i>
                        </div>                            
                    </div>
                </div>
            </div>
        </div>

        <?php } ?>
    </div>

</div>



