<?php 
if(isset($_GET['category'])){
  $category = $_GET['category'];
  $filterByCat = true; 
} else {
  $filterByCat = false; 
}
?>
<script>aurl = 'plugins';</script>

<!-- SECTION CONTENT -->
<div class="container-fluid page__container" style="padding-top:25px;padding-bottom: 50px">
    <?php if($filterByCat){ ?>
      <div class="page__heading d-flex align-items-center">
        <div class="flex">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb mb-0">
                  <li class="breadcrumb-item"><a href="#" onclick="goTo('plugins','','')">Plugins</a></li>
                  <li class="breadcrumb-item active"><a href="#" onclick="goTo('plugins','','<?= $category;?>')">
                    <?= $category;?></a></li>
              </ol>
            </nav>
        </div>
        <a href="#" class="btn btn-light ml-3" onclick="goTo('plugins','','')"><i class="material-icons mr-1">arrow_back</i></a>
      </div>
    <?php } ?>


<div class="card card-form d-flex flex-column flex-sm-row hidem" >
  <div class="card-form__body card-body-form-group flex hidem">
      <div class="row">
          <div class="col-sm-auto" style="min-width: 29%">
              <div class="form-group">
                  <label for="filter_name">Plugin name</label>
              </div>
          </div>
          <div class="col-sm-auto" style="min-width: 40%">
              <div class="form-group">
                  <label for="filter_category">Description</label><br>
              </div>
          </div>
          <div class="col-sm-auto" style="min-width: 8%">
              <div class="form-group">
                  <label for="filter_stock">STATUS</label>
              </div>
          </div>
          <div class="col-sm-auto">
              <div class="form-group" style="min-width: 18%;padding-left: 45px">
                  <label for="filter_date">ACTIONS</label>
              </div>
          </div>
      </div>
  </div>
</div>

<?php 
//get plugins
if($filterByCat){
  $plugins = getDataArrayFull('plugins','where visible = 1 and category = "'.$category.'" ORDER BY orden DESC'); 
}else{
  $plugins = getDataArrayFull('plugins','where visible = 1 ORDER BY orden DESC'); 
}
foreach ($plugins as $p) { ?>
<div class="row align-items-center mb-1" data-plugin-category="<?= $p['category']; ?>">
    <div class="col-sm">
        <div class="card m-0">
            <div class="px-4 py-3">
                <div class="row align-items-center">
                    <div class="col-auto" style="min-width: 5%">
                      <div class="avatar avatar-lg" >
                          <img src="<?= $p['image']; ?>"  class="avatar-img rounded" style="border: 1px solid #f6f6f6">
                      </div>                        
                    </div>                      
                    <div class="col-auto" style="width: 20%">
                        <div class="d-flex align-items-center">
                          <?php if($p['settings'] == 1){ ?>
                            <?php if(!empty($p['custom_url_link'])){ ?>
                              <a href="#" onclick="goTo('<?= $p['custom_url_link']; ?>','','')" class="text-body"><strong class="text-15pt mr-2"><?= $p['title']; ?></strong></a>  
                            <?php } else { ?>
                              <a href="#" onclick="goTo('plugin','<?= $p['name']; ?>','<?= $p['category']; ?>')" class="text-body"><strong class="text-15pt mr-2"><?= $p['title']; ?></strong></a>
                            <?php } ?>  
                            <?php if($p['premium'] == 1){ ?> 
                                <span class="btn btn-warning btn-sm">PREMIUM</span>
                            <?php } ?> 
                          <?php } else { ?>                                                 
                              <a href="javascript:;" style="cursor: default" class="text-body"><strong class="text-15pt mr-2"><?= $p['title']; ?></strong></a>
                              <?php if($p['premium'] == 1){ ?> 
                                  <span class="btn btn-warning btn-sm">PREMIUM</span>
                              <?php } ?>                               
                            <?php } ?>  
                        </div>
                        <div class="d-flex align-items-center">
                            <small class="text-dark-gray mr-2"><?= $p['category']; ?></small>

                        </div>
                    </div>
                    <div class="col-auto text-left" style="width: 40%;padding-top: 15px">
                        <p class="nunito" style="color: #888;font-size: 13px;"><?= $p['info']; ?></p>
                    </div>
                    <div class="col-auto " style="width: 10%">
                        <?php if($p['settings'] == 1){ ?> 
                          <div class="align-items-center">
                          <?php if($p['enabled'] == 1){ ?>                          
                              <span class="btn btn-success btn-sm">ACTIVE</span>
                          <?php } else { ?> 
                              <span class="btn btn-light btn-sm">DISABLED</span>
                          <?php } ?>                                                    
                          </div>  
                        <?php } ?>                       
                    </div>                                               
                    <div class="col-auto text-center" style="width: 15%;left: 10px">
                      <?php if($p['settings'] == 1){ ?> 
                        <?php if(!empty($p['custom_url_link'])){ ?>
                          <a href="#" onclick="goTo('<?= $p['custom_url_link']; ?>','','')" class="btn btn-light" style="font-size: 12px"><i class="material-icons" style="font-size: 15px">settings</i> settings</a>     
                        <?php } else { ?>
                        <a href="#" onclick="goTo('plugin','<?= $p['name']; ?>','<?= $p['category']; ?>')" class="btn btn-light" style="font-size: 12px"><i class="material-icons" style="font-size: 15px">settings</i> settings</a>
                        <?php } ?>                      
                      <?php } ?>
                      <?php if($p['settings'] == 2){ ?> 
                        <a href="https://premiumdatingscript.com/buy-<?= $p['name']; ?>" target="_blank" class="btn btn-warning" style="font-size: 12px"><i class="material-icons" style="font-size: 15px">attach_money</i> Buy now</a>                    
                      <?php } ?>                      
                      
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<?php } ?>

</div>

