<?php
$arr = array();
$arr = profileQuestion(1);
$all = end($arr);
$all = $all['id'] + 1; ?>
<div class="col-lg-12" >   
<div class="card card-form" style="background: none;box-shadow: none">
    <div class="card-header card-header-large bg-white d-flex align-items-center">
      <h4 class="card-header__title flex m-0">
        Possible answers for question type <code>SELECT</code>
      </h4>
    </div>    
    <div class="row no-gutters">
      <?php foreach($arr as $entry){ 
        if($entry['method'] == 'select'){ 
          $answer = array();
          $answer = profileQuestionAnswer($entry['id'],1);
          $c = count($answer);
          $c = $c + 1;          
          ?>
        <div class="col-lg-4" style="padding-right: 10px;padding-top: 10px">
            <div class="card" style="max-height: 450px;min-height: 450px;overflow-y: auto">
                <div class="card-header card-header-large bg-white d-flex align-items-center">
                    <h3 class="card-header__title flex m-0" style="font-weight: bold"><?= $entry['question']; ?></h3>
                    <div>
                      <a class="btn btn-light" data-btn-q="<?= $entry['id']; ?>" onclick="updateAnswers(<?= $entry['id']; ?>,<?= $c; ?>)">Update</a>                            
                    </div>
                </div>
                <div class="card-body bg-light" style="padding:0">
                  <ul class="list-group list-lessons">
                  <?php foreach($answer as $a){ ?>
                      <li class="list-group-item d-flex q-<?= $entry['id']; ?>" contenteditable="true" data-answer="<?= $a['id']; ?>">
                          <?= $a['answer']; ?>
                      </li>
                  <?php } ?>                          
                      <li class="list-group-item d-flex bg-light q-<?= $entry['id']; ?>" placeholder="Add answer" contenteditable="true" data-answer="<?= $c; ?>"></li>
                  </ul>
                </div>
                <div class="card-footer text-center bg-white">
                    <span class="text-muted">Leave the answer empty for remove</span>
                </div>
            </div>
        </div>                
      <?php } 
      }?>   
    </div>
  </div>
</div>