<?php
  if($sm['admin_ajax'] == false){
    header('Location:'.$sm['config']['site_url'].'index.php?page=admin');
  }
?>
<script>
  aurl = 'refManager';
  currentMenu = '';
  currentMenuCollapse = ''; 
</script>
<!-- SECTION CONTENT -->
<div class="container-fluid page__container" id="mediaContainer" style="padding-top:25px;min-height: 800px ">

  <div class="card card-form" >
      <div class="card-header card-header-large bg-white">
          <h4 class="card-header__title">Create referral reward</h4>
      </div>    
      <div class="card-form__body card-body-form-group flex">
          <div class="row">
              <div class="col-sm-3" >
                  <div class="form-group">
                      <label for="filter_id">Name</label>
                      <input id="ref_name" type="text" class="form-control" placeholder="Identifier name">
                  </div>
              </div>
              <div class="col-sm-4">
                  <div class="form-group">
                      <label for="ref_type">Type</label><br>
                      <select id="ref_type" class="custom-select">
                      <?php 
                      $order = 'id asc';
                      $reftype = getArray('referrals_config','WHERE action_name ="type"',$order); 
                      foreach ($reftype as $r) { ?> 
                        <option value="<?= $r['action_val']; ?>"><?= $r['action_val']; ?></option>
                      <?php } ?>
                      </select>
                  </div>
              </div>              
              <div class="col-sm-3">
                  <div class="form-group">
                      <label for="ref_reward">Reward</label><br>
                      <select id="ref_reward" class="custom-select">
                      <?php 
                      $order = 'id asc';
                      $reftype = getArray('referrals_config','WHERE action_name ="reward"',$order); 
                      foreach ($reftype as $r) { ?> 
                        <option value="<?= $r['action_val']; ?>"><?= $r['action_val']; ?></option>
                      <?php } ?>                        
                      </select>
                  </div>
              </div> 
              <div class="col-sm-2">
                  <div class="form-group">
                      <label for="ref_amount">Amount</label><br>
                      <input id="ref_amount" type="text" value="1" class="form-control">
                  </div>
              </div>                                        
          </div>
      </div>
      <button class="btn btn-light border-left border-top border-top-sm-0 rounded-top-0 rounded-top-sm rounded-left-sm-0 " style="outline: none;" onclick="createRef()"><i class="material-icons">link</i> Create referral reward</button>
  </div>

  <div class="card card-form">
      <div class="row no-gutters">
          <div class="col-lg-12 col-md-12 col-sm-12 card-form__body" style="min-height: 700px">              
              <div class="table-responsive border-bottom" data-search data-toggle="lists" data-lists-values='["js-lists-values-employee-name"]' style="min-height: 700px" data-table="result">   


                  <table class="table mb-0 thead-border-top-0" style="">
                      <thead>
                          <tr style="background: #fff">
                              <th style="width: 90px;">Name</th>
                              <th style="width: 280px;">Action</th>
                              <th style="width: 170px;">Reward</th>
                              <th style="width: 40px;">Amount</th>                              
                              <th style="width: 70px;">Status</th>
                              <th style="width: 24px;"></th>
                          </tr>
                      </thead>

                      <tbody class="list" style="overflow-y: scroll">
                      <?php $ref = getArray('referrals','','ref_status DESC'); 
                      foreach ($ref as $r) { 
                        if($r['ref_status'] == 1){
                          $refStatus = 'Active';
                          $refStatusLabel = 'success';
                        $refStatusDropdownActive = 'display:block;';
                        } else {
                          $refStatus = 'Inactive';
                          $refStatusLabel = 'danger';  
                          $refStatusDropdownInactive = 'display:block;';
                        }
                      ?> 
                        <tr class="data-search-verifications">
                          <td><?= $r['ref_name']; ?></td>
                          <td><?= $r['ref_type']; ?></td>
                          <td><?= $r['ref_reward']; ?></td>
                          <td><?= $r['ref_amount']; ?></td>
                          <td>
                            <small class="badge badge-<?=$refStatusLabel; ?>">
                              <?=$refStatus; ?>
                            </small>
                          </td>
                          <td>
                            <div class="dropdown ml-auto">
                                <a href="#" data-toggle="dropdown" data-caret="false" class="btn btn-light text-muted"><i class="material-icons">more_vert</i></a>
                                <div class="dropdown-menu dropdown-menu-right">
                                  <a class="dropdown-item" href="javascript:;" style="font-size: 13px" 
                                  onclick="deleteRef('<?=$r['ref_name']; ?>')">
                                    Delete
                                  </a>
                                </div>
                            </div>
                          </td>                            
                        </tr>
                      <?php } ?>                        
                      </tbody>
                  </table>
              </div>
 

          </div>                    
      </div>
      <div class="card-footer text-center">TO HIDE REFERRALS FROM PUBLIC SITE YOU MUST DON'T HAVE ANY REFERRAL REWARD</div>
  </div>    


</div>


<script>

    var cr = {};
  
    function createRef(){
      cr['action'] = 'create_ref';
      cr['name'] = $('#ref_name').val();
      cr['type'] = $('#ref_type').val();
      cr['reward'] = $('#ref_reward').val();
      cr['amount'] = $('#ref_amount').val();
      if(cr['name'] == '' || cr['name'] === undefined){
        return false;
      }
      $.ajax({
        url: request_source()+'/admin.php', 
        data: cr,  
        type: "post",
        dataType: 'JSON',        
        success: function(response) {
          goTo('refManager','','Tools');
        },
      });   
    } 
   
    function deleteRef(r){
      $.ajax({
        url: request_source()+'/admin.php', 
        data: {
          action: 'delete_ref',
          ref: r
        },  
        type: "post",
        dataType: 'JSON',        
        success: function(response) {
          goTo('refManager','','Tools');
        },
      });      
    }

</script>